export const INPUT_TEXT_MOCKS = {
  DEFAULT_PLACEHOLDER: 'Enter text',
  DEFAULT_VALUE: '',
  
  TEST_VALUE: 'Test',
  TEST_NAME_PLACEHOLDER: 'Name',
  TEST_SEARCH_PLACEHOLDER: 'Search...',

  TYPED_CONTENT: 'Angular 21',
  FORM_INITIAL_VALUE: 'Initial Value',
  FORM_NEW_VALUE: 'New Value',
  SIGNAL_UPDATE_VALUE: 'Not Empty'
};

export const INPUT_TEXT_LABELS = {
  PLACEHOLDER: {
    DEFAULT: INPUT_TEXT_MOCKS.DEFAULT_PLACEHOLDER,
    NAME: INPUT_TEXT_MOCKS.TEST_NAME_PLACEHOLDER,
    SEARCH: INPUT_TEXT_MOCKS.TEST_SEARCH_PLACEHOLDER
  }
};

export const INPUT_TEXT_STATES = {
  DISABLED: true,
  ENABLED: false,
  FOCUSED: true,
  BLURRED: false,
  EMPTY: true,
  NOT_EMPTY: false
};